#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

#import itertools
#import scipy.interpolate
import json
import matplotlib.pyplot as pl
import numpy as np
import scipy.optimize as op
import scipy.signal
import sys
import unitprint

def legierung_peaks(dataname, column_offset=0):
    data = np.genfromtxt(dataname, skip_header=1)

    bins = data[:, 0+column_offset]
    counts = data[:, 1+column_offset]

    peak_indizes = scipy.signal.find_peaks_cwt(counts, np.array([4]))
    peak_indizes = np.array(peak_indizes)

    max_count = np.max(counts)

    real_peaks = [
        peak_index
        for peak_index in peak_indizes
        if counts[peak_index] > max_count * 0.1
    ]

    return real_peaks

def legierung_plot(dataname, real_peaks, linestyle='-', color='blue',
                   column_offset=0, label=None, linewidth=1):
    data = np.genfromtxt(dataname, skip_header=1)

    bins = data[:, 0+column_offset]
    counts = data[:, 1+column_offset]

    counts /= np.max(counts)

    pl.plot(bins, counts, linestyle=linestyle, color=color, label=label, linewidth=linewidth)
    pl.plot(bins[real_peaks], counts[real_peaks], linestyle='none', marker='*', markersize=10, color=color)

def zefn(T):
    fezn_peaks = legierung_peaks('Messdaten/Legierungen/FeZn.txt')

    unbekannt_peaks = legierung_peaks('Messdaten/Legierungen/Probe_1.txt')

    cu_peaks = legierung_peaks('Messdaten/Legierungen/Cu.txt', column_offset=1)
    fe_peaks = legierung_peaks('Messdaten/Legierungen/Fe.txt', column_offset=1)
    mo_peaks = legierung_peaks('Messdaten/Legierungen/Mo.txt', column_offset=1)
    ni_peaks = legierung_peaks('Messdaten/Legierungen/Ni.txt', column_offset=1)
    ti_peaks = legierung_peaks('Messdaten/Legierungen/Ti.txt', column_offset=1)
    zn_peaks = legierung_peaks('Messdaten/Legierungen/Zn.txt', column_offset=1)

    #legierung_plot('Messdaten/Legierungen/FeZn.txt', fezn_peaks)

    legierung_plot('Messdaten/Legierungen/Probe_1.txt', unbekannt_peaks, color='black', label='Probe', linewidth=2)

    linewidth_small = .5

    legierung_plot('Messdaten/Legierungen/Cu.txt', cu_peaks, column_offset=1, color='red', linestyle='-', label='Cu', linewidth=linewidth_small)
    legierung_plot('Messdaten/Legierungen/Fe.txt', fe_peaks, column_offset=1, color='orange', linestyle='-', label='Fe', linewidth=linewidth_small)
    legierung_plot('Messdaten/Legierungen/Mo.txt', mo_peaks, column_offset=1, color='green', linestyle='-', label='Mo', linewidth=linewidth_small)
    legierung_plot('Messdaten/Legierungen/Ni.txt', ni_peaks, column_offset=1, color='cyan', linestyle='-', label='Ni', linewidth=linewidth_small)
    legierung_plot('Messdaten/Legierungen/Ti.txt', ti_peaks, column_offset=1, color='blue', linestyle='-', label='Ti', linewidth=linewidth_small)
    legierung_plot('Messdaten/Legierungen/Zn.txt', zn_peaks, column_offset=1, color='purple', linestyle='-', label='Zn', linewidth=linewidth_small)

    pl.xlabel('Energiekanal')
    pl.ylabel('normalisierte Anzahl')
    pl.xlim([30, 170])
    pl.grid(True)
    pl.legend(loc='best')
    pl.savefig('_build/Bestimmung.pdf')
    pl.clf()

def main():
    T = {}

    zefn(T)

    with open('_build/template.js', 'w') as f:
        json.dump(T, f, indent=4, sort_keys=True)

if __name__ == "__main__":
    main()
