#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

#import scipy.interpolate
import colorsys
import fractions
import itertools
import json
import matplotlib.pyplot as pl
import multiprocessing
import numpy as np
import operator
import scipy.ndimage
import scipy.optimize as op
import scipy.signal
import sys
import unitprint

savefig_options = {
    'bbox_inches': 'tight',
}

def job_zimmertemperatur(T):
    sr540 = strom(T, 'hf_540_strom_', 'Messdaten/InAs-HF-540-Zimmertemperatur-Strom.txt')
    hr540 = hall_mit_nullfeld(T, 'hf_540_hall_', 'Messdaten/InAs-HF-540-Zimmertemperatur-Hall.txt')

    sr301 = strom(T, 'hf_301_strom_', 'Messdaten/InAs-HF-301-040-Zimmertemperatur-Strom.txt')
    hr301 = hall_mit_nullfeld(T, 'hf_301_hall_', 'Messdaten/InAs-HF-301-040-Zimmertemperatur-Hall.txt')

    results = [
        [r'\probeA', unitprint.siunitx(*sr540), unitprint.siunitx(*hr540[0:2]), unitprint.siunitx(*hr540[2:4]), unitprint.siunitx(*hr540[4:6])],
        [r'\probeB', unitprint.siunitx(*sr301), unitprint.siunitx(*hr301[0:2]), unitprint.siunitx(*hr301[2:4]), unitprint.siunitx(*hr301[4:6])],
    ]

    T['zimmertemperatur_tabelle'] = results

def strom(T, prefix, messdaten):
    data = np.genfromtxt(messdaten)
    n = data[:, 0]
    V = data[:, 1] * 10**-3

    I = 13.601e-3

    R1234 = abs(V[n==1] - V[n==2]) / (2 * I)
    R2341 = abs(V[n==3] - V[n==4]) / (2 * I)

    rho1 = np.pi / np.log(2) * (R1234 + R2341) / 2

    R3412 = abs(V[n==3] - V[n==4]) / (2 * I)
    R4132 = abs(V[n==4] - V[n==1]) / (2 * I)
    rho2 = np.pi / np.log(2) * (R3412 + R4132) / 2

    rho = (rho1 + rho2) / 2

    rho_val = np.mean(rho)
    rho_err = np.std(rho) / np.sqrt(len(rho))

    digits = 4

    T[prefix+'R_tabelle'] = list(zip(
        unitprint.siunitx(R1234, digits=digits),
        unitprint.siunitx(R2341, digits=digits),
        unitprint.siunitx(R3412, digits=digits),
        unitprint.siunitx(R4132, digits=digits),
        unitprint.siunitx(R1234/R2341, digits=digits),
        unitprint.siunitx(R3412/R4132, digits=digits),
    ))
    T[prefix+'rho_tabelle'] = list(zip(
        unitprint.siunitx(rho1, digits=digits),
        unitprint.siunitx(rho2, digits=digits),
        unitprint.siunitx(rho, digits=digits),
    ))
    T[prefix+'rho'] = unitprint.siunitx(rho_val, rho_err)

    return rho_val, rho_err

def hall_mit_nullfeld(T, prefix, messdaten):
    data = np.genfromtxt(messdaten)
    n = data[:, 0]
    V = data[:, 1] * 10**-3

    I = 13.601e-3

    B = 0.138

    dV_A = V[n==1] - V[n==9]
    dV_B = V[n==2] - V[n==10]
    dV_C = V[n==5] - V[n==9]
    dV_D = V[n==6] - V[n==10]

    V_H_plus = (dV_A - dV_B) / 2
    V_H_minus = (dV_C - dV_D) / 2

    R_H_plus = V_H_plus / (B * I)
    R_H_minus = - V_H_minus / (B * I)

    digits = 4

    T[prefix+'V_tabelle'] = list(zip(
        unitprint.siunitx(dV_A, digits=digits),
        unitprint.siunitx(dV_B, digits=digits),
        unitprint.siunitx(dV_C, digits=digits),
        unitprint.siunitx(dV_D, digits=digits),
    ))
    T[prefix+'V_R_tabelle'] = list(zip(
        unitprint.siunitx(V_H_plus, digits=digits),
        unitprint.siunitx(V_H_minus, digits=digits),
        unitprint.siunitx(R_H_plus, digits=digits),
        unitprint.siunitx(R_H_minus, digits=digits),
    ))

    R_H_plus_val = np.mean(R_H_plus)
    R_H_plus_err = np.std(R_H_plus) / np.sqrt(len(R_H_plus))
    T[prefix+'R_H_plus'] = unitprint.siunitx(R_H_plus_val, R_H_plus_err)

    R_H_minus_val = np.mean(R_H_minus)
    R_H_minus_err = np.std(R_H_minus) / np.sqrt(len(R_H_minus))
    T[prefix+'R_H_minus'] = unitprint.siunitx(R_H_minus_val, R_H_minus_err)

    R_H1 = 1 / (B * I) * ((V[n==1] - V[n==2]) - (V[n==5] - V[n==6])) / 4
    R_H2 = 1 / (B * I) * ((V[n==3] - V[n==4]) - (V[n==7] - V[n==8])) / 4

    R_H = (R_H1 + R_H2) / 2

    T[prefix+'RH_mit_tabelle'] = list(zip(
        unitprint.siunitx(R_H1, digits=digits),
        unitprint.siunitx(R_H2, digits=digits),
        unitprint.siunitx(R_H, digits=digits),
    ))

    R_H_val = np.mean(R_H)
    R_H_err = np.std(R_H) / np.sqrt(len(R_H))

    T[prefix+'R_H'] = unitprint.siunitx(R_H_val, R_H_err)

    return R_H_plus_val, R_H_plus_err, R_H_minus_val, R_H_minus_err, R_H_val, R_H_err

def main():
    with multiprocessing.Manager() as manager:
        T = manager.dict()

        l = globals()
        to_run = []
        for key, value in l.items():
            if key.startswith('job_'):
                to_run.append(value)

        print('Will run the following functions:')
        for f in to_run:
            print('-', f)

        processes = []
        for f in to_run:
            p = multiprocessing.Process(target=f, args=(T,))
            print("Starting", p)
            p.start()
            processes.append(p)

        for p in processes:
            print("Waiting for", p)
            p.join()

        print("Serializing …")

        with open('_build/template.js', 'w') as f:
            json.dump(dict(T), f, indent=4, sort_keys=True)

if __name__ == "__main__":
    main()
