#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2013 Martin Ueding <dev@martin-ueding.de>
# Licensed under The GNU Public License Version 2 (or later)

import jinja2
import json
import sys

def render_template(filename):
    # Setting up Jinja
    env = jinja2.Environment(
        "%<", ">%",
        "<<", ">>",
        "%§", "§%",
        loader=jinja2.FileSystemLoader(".")
    )
    template = env.get_template("Template.tex")

    with open('_build/template.js') as f:
        T = json.load(f)

    # Rendering LaTeX document with values.
    with open(filename, "w") as f:
        f.write(template.render(**T))

if __name__ == '__main__':
    if len(sys.argv) > 1:
        render_template(sys.argv[1])
    else:
        print('Keine Ausgabe, da Dateiname fehlt.')
